const types={image:{accept:'image/jpeg,image/png,image/webp',label:'Foto JPG, PNG, WEBP'},audio:{accept:'audio/mpeg,audio/wav,audio/mp4,audio/ogg,audio/webm,audio/flac',label:'Audio MP3, WAV, M4A, OGG'},video:{accept:'video/mp4,video/quicktime,video/webm',label:'Video MP4, MOV, WEBM'},text:{accept:'text/plain',label:'Teks TXT'}};
const maxSize=4*1024*1024;let selectedType='image';let selectedFile=null;
const $=id=>document.getElementById(id);const fileInput=$('evidence-file');const dropZone=$('drop-zone');
function setupMenu(){const menu=$('menu-button'),side=$('sidebar'),overlay=$('overlay');const toggle=()=>{side.classList.toggle('open');overlay.classList.toggle('open')};menu?.addEventListener('click',toggle);overlay?.addEventListener('click',toggle)}
function showAlert(message,error=false){const el=$('form-alert');el.textContent=message;el.className=`alert${error?' error':''}`;el.scrollIntoView({behavior:'smooth',block:'nearest'})}
function humanSize(bytes){return bytes<1024*1024?`${Math.round(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(2)} MB`}
function validForType(file){if(selectedType==='text')return file.type==='text/plain'||file.name.toLowerCase().endsWith('.txt');return file.type.startsWith(`${selectedType}/`)}
function chooseFile(file){if(!file)return;if(!validForType(file)){showAlert(`File tidak sesuai dengan jenis ${selectedType}.`,true);return}if(file.size>maxSize){showAlert('Ukuran file melebihi 4 MB. Untuk versi saat ini pilih file yang lebih kecil.',true);return}selectedFile=file;$('file-name').textContent=file.name;$('file-meta').textContent=`${humanSize(file.size)} • ${file.type||'file'}`;$('file-icon').textContent={image:'▧',audio:'♫',video:'▶',text:'¶'}[selectedType];$('file-preview').classList.remove('hidden');$('form-alert').classList.add('hidden')}
document.querySelectorAll('.type-card').forEach(button=>button.addEventListener('click',()=>{selectedType=button.dataset.type;document.querySelectorAll('.type-card').forEach(x=>x.classList.toggle('active',x===button));fileInput.accept=types[selectedType].accept;$('file-rule').textContent=`${types[selectedType].label} • maksimal 4 MB`;fileInput.value='';selectedFile=null;$('file-preview').classList.add('hidden')}));
fileInput.addEventListener('change',()=>chooseFile(fileInput.files[0]));['dragenter','dragover'].forEach(name=>dropZone.addEventListener(name,e=>{e.preventDefault();dropZone.classList.add('dragover')}));['dragleave','drop'].forEach(name=>dropZone.addEventListener(name,e=>{e.preventDefault();dropZone.classList.remove('dragover')}));dropZone.addEventListener('drop',e=>chooseFile(e.dataTransfer.files[0]));$('remove-file').addEventListener('click',()=>{selectedFile=null;fileInput.value='';$('file-preview').classList.add('hidden')});$('chronology').addEventListener('input',e=>$('char-count').textContent=e.target.value.length);
$('evidence-form').addEventListener('submit',async e=>{e.preventDefault();if(!selectedFile){showAlert('Pilih satu file bukti terlebih dahulu.',true);return}const button=$('submit-button');button.disabled=true;button.textContent='Menyimpan...';try{const reports=JSON.parse(localStorage.getItem('ruangAman_reports')||'[]');const now=new Date();const report={id:`RA-${now.getFullYear()}-${String(Date.now()).slice(-5)}`,title:$('case-title').value.trim(),createdAt:now.toISOString(),incidentAt:$('incident-date').value,type:selectedType,status:'Diproses',location:$('incident-location').value.trim()||'Tidak dicantumkan',fileName:selectedFile.name,chronology:$('chronology').value.trim(),summary:'Bukti telah diterima. Ringkasan ML akan tampil setelah proses analisis selesai.',points:['File berhasil diterima','Menunggu hasil pengolahan OCR/transkripsi dan ringkasan'],timeline:[{label:'Laporan dibuat',date:now.toISOString()},{label:'Bukti menunggu diproses',date:now.toISOString()}]};reports.unshift(report);localStorage.setItem('ruangAman_reports',JSON.stringify(reports));showAlert('Laporan berhasil disimpan. Membuka halaman laporan...');setTimeout(()=>location.href=`report-detail.html?id=${encodeURIComponent(report.id)}`,700)}catch(error){showAlert('Laporan belum dapat disimpan. Silakan coba kembali.',true);button.disabled=false;button.textContent='Kirim untuk diproses →'}});
setupMenu();
